package split_table

import (
	"fmt"
	"testing"

	"vitess.io/vitess/go/test/endtoend/utils"
)

func Test_Explain(t *testing.T) {
	mcmp, closer := start(t)
	defer closer()
	mcmp.Exec("use user")

	for i := 1; i <= 1000; i++ {
		query := fmt.Sprintf("INSERT INTO zcorder1 (order_id, customer_id, product_id, country, default_id, order_date, total_amount, quantity, unit_price, string, sequence_id) VALUES (%d, %d, %d, 'China', 63, '2023-11-11', 10.00, 5, 2.00, 'zhuchen63', %d)",
			i, i, i, i)
		mcmp.Exec(query)
	}

	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, customer_id, product_id, country, default_id, order_date, total_amount, quantity, unit_price, string, sequence_id FROM zcorder1 ORDER BY order_id DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, customer_id, product_id, country, default_id, order_date, total_amount, quantity, unit_price, string, sequence_id FROM zcorder1 ORDER BY order_id ASC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, customer_id, product_id, country, default_id, order_date, total_amount, quantity, unit_price, string, sequence_id FROM zcorder1 ORDER BY order_date DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, customer_id, product_id, country, default_id, order_date, total_amount, quantity, unit_price, string, sequence_id FROM zcorder1 ORDER BY order_date ASC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, customer_id, product_id, country, default_id, order_date, total_amount, quantity, unit_price, string, sequence_id FROM zcorder1 ORDER BY customer_id DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, customer_id, product_id, country, default_id, order_date, total_amount, quantity, unit_price, string, sequence_id FROM zcorder1 ORDER BY customer_id ASC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, customer_id, product_id, country, default_id, order_date, total_amount, quantity, unit_price, string, sequence_id FROM zcorder1 ORDER BY product_id DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, customer_id, product_id, country, default_id, order_date, total_amount, quantity, unit_price, string, sequence_id FROM zcorder1 ORDER BY product_id ASC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, customer_id, product_id, country, default_id, order_date, total_amount, quantity, unit_price, string, sequence_id FROM zcorder1 ORDER BY sequence_id DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, customer_id, product_id, country, default_id, order_date, total_amount, quantity, unit_price, string, sequence_id FROM zcorder1 ORDER BY sequence_id ASC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, total_amount FROM zcorder1")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, total_amount FROM zcorder1 WHERE customer_id = 63")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, total_amount FROM zcorder1 GROUP BY customer_id")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, total_amount FROM zcorder1 ORDER BY order_id DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, total_amount FROM zcorder1 LIMIT 10")
	utils.Exec(t, mcmp.VtConn, "explain SELECT COUNT(*) FROM zcorder1")
	utils.Exec(t, mcmp.VtConn, "explain SELECT MAX(total_amount) FROM zcorder1")
	utils.Exec(t, mcmp.VtConn, "explain SELECT MIN(total_amount) FROM zcorder1")
	utils.Exec(t, mcmp.VtConn, "explain SELECT SUM(total_amount) FROM zcorder1")
	utils.Exec(t, mcmp.VtConn, "explain SELECT customer_id, COUNT(*) FROM zcorder1 GROUP BY customer_id")
	utils.Exec(t, mcmp.VtConn, "explain SELECT customer_id, MAX(total_amount) FROM zcorder1 GROUP BY customer_id")
	utils.Exec(t, mcmp.VtConn, "explain SELECT customer_id, MIN(total_amount) FROM zcorder1 GROUP BY customer_id")
	utils.Exec(t, mcmp.VtConn, "explain SELECT customer_id FROM zcorder1 GROUP BY customer_id")
	utils.Exec(t, mcmp.VtConn, "explain SELECT customer_id, SUM(total_amount) FROM zcorder1 GROUP BY customer_id")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 WHERE customer_id = 63 ORDER BY order_date DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 WHERE order_date = '2023-10-25' LIMIT 10")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, total_amount FROM zcorder1 WHERE customer_id = 63 GROUP BY order_date")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, total_amount FROM zcorder1 WHERE customer_id = 63 ORDER BY order_date DESC LIMIT 10")
	utils.Exec(t, mcmp.VtConn, "explain SELECT COUNT(*) FROM zcorder1 WHERE customer_id = 63")
	utils.Exec(t, mcmp.VtConn, "explain SELECT MAX(total_amount) FROM zcorder1 WHERE customer_id = 63")
	utils.Exec(t, mcmp.VtConn, "explain SELECT MIN(total_amount) FROM zcorder1 WHERE customer_id = 63")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 WHERE customer_id = 63 limit 100")
	utils.Exec(t, mcmp.VtConn, "explain SELECT SUM(total_amount) FROM zcorder1 WHERE customer_id = 63")
	utils.Exec(t, mcmp.VtConn, "explain SELECT customer_id, COUNT(*) FROM zcorder1 WHERE order_date = '2023-10-25' GROUP BY customer_id")
	utils.Exec(t, mcmp.VtConn, "explain SELECT customer_id, MAX(total_amount) FROM zcorder1 WHERE order_date = '2023-10-25' GROUP BY customer_id")
	utils.Exec(t, mcmp.VtConn, "explain SELECT customer_id, MIN(total_amount) FROM zcorder1 WHERE order_date = '2023-10-25' GROUP BY customer_id")
	utils.Exec(t, mcmp.VtConn, "explain SELECT customer_id FROM zcorder1 WHERE order_date = '2023-10-25' GROUP BY customer_id")
	utils.Exec(t, mcmp.VtConn, "explain SELECT customer_id, SUM(total_amount) FROM zcorder1 WHERE order_date = '2023-10-25' GROUP BY customer_id")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 WHERE customer_id = 652994 ORDER BY order_date DESC LIMIT 10")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 WHERE order_date = '2023-10-25' ORDER BY total_amount ASC LIMIT 10")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, total_amount FROM zcorder1 WHERE customer_id = 63 GROUP BY order_date ORDER BY total_amount DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, total_amount FROM zcorder1 WHERE customer_id = 63 ORDER BY order_date DESC LIMIT 10")
	utils.Exec(t, mcmp.VtConn, "explain SELECT COUNT(*) FROM zcorder1 WHERE customer_id = 63 AND order_date = '2023-10-25'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT MAX(total_amount) FROM zcorder1 WHERE customer_id = 63 AND order_date = '2023-10-25'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT MIN(total_amount) FROM zcorder1 WHERE customer_id = 63 AND order_date = '2023-10-25'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT country FROM zcorder1 WHERE customer_id = 63 AND order_date = '2023-10-25'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT SUM(total_amount) FROM zcorder1 WHERE customer_id = 63 AND order_date = '2023-10-25'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT customer_id, COUNT(*) FROM zcorder1 WHERE order_date = '2023-10-25' GROUP BY customer_id ORDER BY COUNT(*) DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, total_amount FROM zcorder1 WHERE order_date = '2023-10-25' ORDER BY total_amount ASC LIMIT 10")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, total_amount FROM zcorder1 WHERE order_date > '2023-10-25' GROUP BY customer_id ORDER BY total_amount DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, total_amount FROM zcorder1 WHERE order_date > '2023-10-25' GROUP BY default_id ORDER BY total_amount DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, total_amount FROM zcorder1 WHERE order_date = '2023-10-25' ORDER BY total_amount DESC LIMIT 10")
	utils.Exec(t, mcmp.VtConn, "explain SELECT COUNT(*) FROM zcorder1 WHERE order_date = '2023-10-25'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT MAX(total_amount) FROM zcorder1 WHERE order_date = '2023-10-25'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT MIN(total_amount) FROM zcorder1 WHERE order_date = '2023-10-25'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT customer_id and total_amount FROM zcorder1 WHERE order_date = '2023-10-25'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT SUM(total_amount) FROM zcorder1 WHERE order_date = '2023-10-25'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT customer_id, COUNT(*) FROM zcorder1 WHERE customer_id = 63 GROUP BY order_date ORDER BY COUNT(*) DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT customer_id, MAX(total_amount) FROM zcorder1 WHERE customer_id = 63 GROUP BY order_date ORDER BY MAX(total_amount) DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT customer_id, MIN(total_amount) FROM zcorder1 WHERE customer_id = 63 GROUP BY order_date ORDER BY MIN(total_amount) ASC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT customer_id, country FROM zcorder1 WHERE customer_id = 63 GROUP BY order_date ORDER BY product_id DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT customer_id, SUM(total_amount) FROM zcorder1 WHERE customer_id = 63 GROUP BY order_date ORDER BY SUM(total_amount) DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 WHERE customer_id = 652994 AND order_date = '2023-01-05' ORDER BY total_amount DESC LIMIT 10")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 WHERE customer_id = 652994 AND order_date = '2023-01-05' ORDER BY order_id ASC LIMIT 10")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 WHERE order_date = '2023-10-25' ORDER BY total_amount DESC, order_id ASC LIMIT 10")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, total_amount FROM zcorder1 WHERE customer_id = 63 AND order_date = '2023-10-25' GROUP BY order_date HAVING COUNT(*) > 1")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, total_amount FROM zcorder1 WHERE customer_id = 63 AND order_date = '2023-10-25' GROUP BY order_date HAVING SUM(total_amount) > 1000")
	utils.Exec(t, mcmp.VtConn, "explain SELECT COUNT(*) FROM zcorder1 WHERE customer_id = 63 AND order_date > '2023-01-01' AND order_date < '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT MAX(total_amount) FROM zcorder1 WHERE customer_id = 63 AND order_date > '2023-01-01' AND order_date < '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT MIN(total_amount) FROM zcorder1 WHERE customer_id = 63 AND order_date > '2023-01-01' AND order_date < '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT string FROM zcorder1 WHERE customer_id = 63 AND order_date > '2023-01-01' AND order_date < '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT SUM(total_amount) FROM zcorder1 WHERE customer_id = 63 AND order_date > '2023-01-01' AND order_date < '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT customer_id, COUNT(*) FROM zcorder1 WHERE order_date > '2023-01-01' AND order_date < '2023-12-31' GROUP BY customer_id ORDER BY COUNT(*) DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT customer_id, string FROM zcorder1 WHERE order_date > '2023-01-01' AND order_date < '2023-12-31' GROUP BY customer_id ORDER BY customer_id DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT customer_id, SUM(total_amount) FROM zcorder1 WHERE order_date > '2023-01-01' AND order_date < '2023-12-31' GROUP BY customer_id ORDER BY SUM(total_amount) DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 WHERE customer_id = 63 AND order_date > '2023-01-01' AND order_date < '2023-12-31' ORDER BY order_date ASC LIMIT 10")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 WHERE order_date > '2023-01-01' AND order_date < '2023-12-31' ORDER BY order_date DESC, total_amount DESC LIMIT 10")
	utils.Exec(t, mcmp.VtConn, "explain SELECT COUNT(*) FROM zcorder1 WHERE customer_id = 63 AND order_date > '2023-01-01' AND order_date < '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT MAX(total_amount) FROM zcorder1 WHERE customer_id = 63 AND order_date > '2023-01-01' AND order_date < '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT MIN(total_amount) FROM zcorder1 WHERE customer_id = 63 AND order_date > '2023-01-01' AND order_date < '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT quantity FROM zcorder1 WHERE customer_id = 63 AND order_date > '2023-01-01' AND order_date < '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT SUM(total_amount) FROM zcorder1 WHERE customer_id = 63 AND order_date > '2023-01-01' AND order_date < '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT customer_id, COUNT(*) FROM zcorder1 WHERE order_date > '2023-01-01' AND order_date < '2023-12-31' GROUP BY customer_id ORDER BY order_id DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT customer_id, SUM(total_amount) FROM zcorder1 WHERE order_date > '2023-01-01' AND order_date < '2023-12-31' GROUP BY customer_id ORDER BY SUM(total_amount) DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 WHERE customer_id = 63 AND order_date > '2023-01-01' AND order_date < '2023-12-31' ORDER BY order_date ASC LIMIT 10")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31' ORDER BY order_date ASC, total_amount DESC LIMIT 10")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31' AND total_amount > 1000 ORDER BY total_amount DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT customer_id, count(*) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31' GROUP BY customer_id")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31' AND customer_id IN (SELECT customer_id FROM zcorder1 WHERE country = 'China') ORDER BY order_date ASC LIMIT 10")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, total_amount FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31' AND customer_id IN (SELECT customer_id FROM zcorder1 WHERE country = 'ChangSha') ORDER BY total_amount DESC LIMIT 10")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, total_amount FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31' AND customer_id IN (SELECT customer_id FROM zcorder1 WHERE country = 'China') ORDER BY order_id DESC LIMIT 10")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_id, total_amount FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31' AND customer_id IN (SELECT customer_id FROM zcorder1 WHERE country <> 'China') ORDER BY order_id DESC LIMIT 10")
	utils.Exec(t, mcmp.VtConn, "explain SELECT customer_id FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31' AND total_amount > (SELECT SUM(quantity) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31') ORDER BY total_amount DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT country FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31' AND total_amount > (SELECT MAX(total_amount) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31') ORDER BY total_amount DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT order_date FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31' AND customer_id IN (SELECT customer_id FROM zcorder1 WHERE country = 'China') ORDER BY order_date ASC, total_amount DESC LIMIT 10")
	utils.Exec(t, mcmp.VtConn, "explain SELECT COUNT(DISTINCT customer_id), MIN(total_amount), MAX(total_amount) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT  SUM(quantity), MAX(unit_price) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT SUM(total_amount),  COUNT(DISTINCT product_id) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT MIN(unit_price), MAX(unit_price) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT COUNT(DISTINCT order_id),  SUM(quantity), MAX(unit_price) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT SUM(quantity), MAX(unit_price), MIN(total_amount) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT COUNT(DISTINCT customer_id), MIN(total_amount), MAX(total_amount) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT SUM(total_amount),  COUNT(DISTINCT product_id), MAX(total_amount) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT MIN(unit_price), MAX(unit_price), COUNT(DISTINCT order_id) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT SUM(quantity), MAX(unit_price), MIN(total_amount) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT SUM(quantity), MAX(unit_price), MIN(total_amount), COUNT(DISTINCT customer_id) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT MIN(total_amount), MAX(total_amount), SUM(total_amount) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT SUM(total_amount), COUNT(DISTINCT product_id), MAX(total_amount), MIN(unit_price) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT MIN(unit_price), MAX(unit_price), COUNT(DISTINCT order_id), SUM(quantity) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT SUM(quantity), MAX(unit_price), MIN(total_amount) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT SUM(quantity), MAX(unit_price), MIN(total_amount), COUNT(DISTINCT customer_id), MIN(unit_price) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT MIN(total_amount), MAX(total_amount), SUM(total_amount) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT MIN(unit_price), MAX(unit_price), SUM(quantity) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT SUM(quantity), MAX(unit_price), MIN(total_amount) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	utils.Exec(t, mcmp.VtConn, "explain SELECT MAX(total_amount), MIN(quantity) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31' GROUP BY product_id ORDER BY product_id ASC LIMIT 10")
	utils.Exec(t, mcmp.VtConn, "explain SELECT MAX(total_amount), MIN(quantity) FROM zcorder1 WHERE product_id = 123 GROUP BY customer_id, order_date ORDER BY order_date DESC LIMIT 100")
	utils.Exec(t, mcmp.VtConn, "explain SELECT customer_id, count(*) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31' GROUP BY customer_id")
	utils.Exec(t, mcmp.VtConn, "explain SELECT MAX(total_amount), MIN(quantity) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31' GROUP BY customer_id, product_id ORDER BY product_id DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT customer_id, string FROM zcorder1 WHERE order_date > '2023-01-01' AND order_date < '2023-12-31' GROUP BY customer_id ORDER BY sum(total_amount) DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 ORDER BY order_id DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 ORDER BY order_id ASC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 ORDER BY order_date DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 ORDER BY order_date ASC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 ORDER BY customer_id DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 ORDER BY customer_id ASC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 ORDER BY product_id DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 ORDER BY product_id ASC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 ORDER BY sequence_id DESC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 ORDER BY sequence_id ASC")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 limit 10")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 WHERE customer_id = 63")
	utils.Exec(t, mcmp.VtConn, "explain SELECT * FROM zcorder1 WHERE order_date = '2023-10-25'")

}
