package split_table

import (
	"fmt"
	"testing"

	"vitess.io/vitess/go/test/endtoend/utils"
)

func TestSelectAlpha(t *testing.T) {
	mcmp, closer := start(t)
	defer closer()
	mcmp.Exec("use user")

	for i := 1; i <= 100; i++ {
		query := fmt.Sprintf("INSERT INTO zcorder1 (order_id, customer_id, product_id, country, default_id, order_date, total_amount, quantity, unit_price, string, sequence_id) VALUES (%d, %d, %d, 'China', 63, '2023-11-11', 10.00, 5, 2.00, 'zhuchen63', %d)",
			i, i, i, i)
		mcmp.Exec(query)
	}

	//mcmp.ExecWithColumnCompareAndNotEmpty("select * from zcorder1 where customer_id =2 order by order_id FOR UPDATE ")
	mcmp.ExecAndNotEmpty("SELECT * from zcorder1 ORDER BY order_id")
	mcmp.ExecAndNotEmpty("SELECT order_id, customer_id, product_id, country, default_id, order_date, total_amount, quantity, unit_price, string, sequence_id FROM zcorder1 ORDER BY order_id DESC")
	mcmp.ExecAndNotEmpty("SELECT order_id, customer_id, product_id, country, default_id, order_date, total_amount, quantity, unit_price, string, sequence_id FROM zcorder1 ORDER BY order_id ASC")
	mcmp.ExecAndNotEmpty("SELECT order_id, customer_id, product_id, country, default_id, order_date, total_amount, quantity, unit_price, string, sequence_id FROM zcorder1 ORDER BY order_date DESC")
	mcmp.ExecAndNotEmpty("SELECT order_id, customer_id, product_id, country, default_id, order_date, total_amount, quantity, unit_price, string, sequence_id FROM zcorder1 ORDER BY order_date ASC")
	mcmp.ExecAndNotEmpty("SELECT order_id, customer_id, product_id, country, default_id, order_date, total_amount, quantity, unit_price, string, sequence_id FROM zcorder1 ORDER BY customer_id DESC")
	mcmp.ExecAndNotEmpty("SELECT order_id, customer_id, product_id, country, default_id, order_date, total_amount, quantity, unit_price, string, sequence_id FROM zcorder1 ORDER BY customer_id ASC")
	mcmp.ExecAndNotEmpty("SELECT order_id, customer_id, product_id, country, default_id, order_date, total_amount, quantity, unit_price, string, sequence_id FROM zcorder1 ORDER BY product_id DESC")
	mcmp.ExecAndNotEmpty("SELECT order_id, customer_id, product_id, country, default_id, order_date, total_amount, quantity, unit_price, string, sequence_id FROM zcorder1 ORDER BY product_id ASC")
	mcmp.ExecAndNotEmpty("SELECT order_id, customer_id, product_id, country, default_id, order_date, total_amount, quantity, unit_price, string, sequence_id FROM zcorder1 ORDER BY sequence_id DESC")
	mcmp.ExecAndNotEmpty("SELECT order_id, customer_id, product_id, country, default_id, order_date, total_amount, quantity, unit_price, string, sequence_id FROM zcorder1 ORDER BY sequence_id ASC")
	mcmp.ExecAndNotEmpty("SELECT order_id, total_amount FROM zcorder1")
	mcmp.ExecAndNotEmpty("SELECT order_id, total_amount FROM zcorder1 WHERE customer_id = 10")
	mcmp.ExecAndNotEmpty("SELECT order_id, total_amount FROM zcorder1 GROUP BY customer_id ORDER BY order_id DESC")
	utils.Exec(t, mcmp.VtConn, "SELECT order_id, total_amount FROM zcorder1 ORDER BY order_id DESC")
	utils.Exec(t, mcmp.VtConn, "SELECT order_id, total_amount FROM zcorder1 LIMIT 10")
	mcmp.ExecAndNotEmpty("SELECT COUNT(*) FROM zcorder1")
	mcmp.ExecAndNotEmpty("SELECT MAX(total_amount) FROM zcorder1")
	mcmp.ExecAndNotEmpty("SELECT MIN(total_amount) FROM zcorder1")
	mcmp.ExecAndNotEmpty("SELECT SUM(total_amount) FROM zcorder1")
	mcmp.ExecAndNotEmpty("SELECT customer_id, COUNT(*) FROM zcorder1 GROUP BY customer_id")
	mcmp.ExecAndNotEmpty("SELECT customer_id, MAX(total_amount) FROM zcorder1 GROUP BY customer_id")
	mcmp.ExecAndNotEmpty("SELECT customer_id, MIN(total_amount) FROM zcorder1 GROUP BY customer_id")
	mcmp.ExecAndNotEmpty("SELECT customer_id FROM zcorder1 GROUP BY customer_id")
	mcmp.ExecAndNotEmpty("SELECT customer_id, SUM(total_amount) FROM zcorder1 GROUP BY customer_id")
	mcmp.ExecAndNotEmpty("SELECT * FROM zcorder1 WHERE customer_id = 10 ORDER BY order_date DESC")
	utils.Exec(t, mcmp.VtConn, "SELECT * FROM zcorder1 WHERE order_date = '2023-11-11' LIMIT 10")
	mcmp.ExecAndNotEmpty("SELECT order_id, total_amount FROM zcorder1 WHERE customer_id = 10 GROUP BY order_date")
	mcmp.ExecAndNotEmpty("SELECT order_id, total_amount FROM zcorder1 WHERE customer_id = 10 ORDER BY order_date DESC LIMIT 10")
	mcmp.ExecAndNotEmpty("SELECT COUNT(*) FROM zcorder1 WHERE customer_id = 5")
	mcmp.ExecAndNotEmpty("SELECT MAX(total_amount) FROM zcorder1 WHERE customer_id = 8")
	mcmp.ExecAndNotEmpty("SELECT MIN(total_amount) FROM zcorder1 WHERE customer_id = 10")
	mcmp.ExecAndNotEmpty("SELECT * FROM zcorder1 WHERE customer_id = 10 limit 100")
	mcmp.ExecAndNotEmpty("SELECT SUM(total_amount) FROM zcorder1 WHERE customer_id = 10")
	mcmp.ExecAndNotEmpty("SELECT customer_id, COUNT(*) FROM zcorder1 WHERE order_date = '2023-11-11' GROUP BY customer_id")
	mcmp.ExecAndNotEmpty("SELECT customer_id, MAX(total_amount) FROM zcorder1 WHERE order_date = '2023-11-11' GROUP BY customer_id")
	mcmp.ExecAndNotEmpty("SELECT customer_id, MIN(total_amount) FROM zcorder1 WHERE order_date = '2023-11-11' GROUP BY customer_id")
	mcmp.ExecAndNotEmpty("SELECT customer_id FROM zcorder1 WHERE order_date > '2023-10-25' GROUP BY customer_id")
	mcmp.ExecAndNotEmpty("SELECT customer_id, SUM(total_amount) FROM zcorder1 WHERE order_date > '2023-10-25' GROUP BY customer_id")
	mcmp.ExecAndNotEmpty("SELECT * FROM zcorder1 WHERE customer_id = 88 ORDER BY order_id DESC LIMIT 10")
	mcmp.ExecAndNotEmpty("SELECT * FROM zcorder1 WHERE order_date > '2023-10-25' ORDER BY customer_id ASC LIMIT 10")
	mcmp.ExecAndNotEmpty("SELECT order_id, total_amount FROM zcorder1 WHERE customer_id = 10 GROUP BY order_date ORDER BY total_amount DESC")
	mcmp.ExecAndNotEmpty("SELECT order_id, total_amount FROM zcorder1 WHERE customer_id = 10 ORDER BY order_date DESC LIMIT 10")
	mcmp.ExecAndNotEmpty("SELECT COUNT(*) FROM zcorder1 WHERE customer_id = 10 AND order_date = '2023-10-25'")
	mcmp.ExecAndNotEmpty("SELECT MAX(total_amount) FROM zcorder1 WHERE customer_id = 10 AND order_date > '2023-10-25'")
	mcmp.ExecAndNotEmpty("SELECT MIN(total_amount) FROM zcorder1 WHERE customer_id = 10 AND order_date > '2023-10-25'")
	mcmp.ExecAndNotEmpty("SELECT country FROM zcorder1 WHERE customer_id = 10 AND order_date = '2023-11-11'")
	mcmp.ExecAndNotEmpty("SELECT SUM(total_amount) FROM zcorder1 WHERE customer_id = 10 AND order_date > '2023-10-25'")
	mcmp.ExecAndNotEmpty("SELECT customer_id, COUNT(*) FROM zcorder1 WHERE order_date = '2023-11-11' GROUP BY customer_id ORDER BY COUNT(*) DESC")
	mcmp.ExecAndNotEmpty("SELECT order_id, total_amount FROM zcorder1 WHERE order_date = '2023-11-11' ORDER BY sequence_id ASC LIMIT 10")
	mcmp.ExecAndNotEmpty("SELECT order_id, total_amount FROM zcorder1 WHERE order_date > '2023-10-25' GROUP BY customer_id ORDER BY customer_id DESC")
	utils.Exec(t, mcmp.VtConn, "SELECT order_id, total_amount FROM zcorder1 WHERE order_date > '2023-10-25' GROUP BY default_id ORDER BY customer_id DESC")
	mcmp.ExecAndNotEmpty("SELECT order_id, total_amount FROM zcorder1 WHERE order_date < '2023-12-12' ORDER BY product_id DESC LIMIT 10")
	mcmp.ExecAndNotEmpty("SELECT COUNT(*) FROM zcorder1 WHERE order_date > '2023-10-25'")
	mcmp.ExecAndNotEmpty("SELECT MAX(total_amount) FROM zcorder1 WHERE order_date > '2023-10-25'")
	mcmp.ExecAndNotEmpty("SELECT MIN(total_amount) FROM zcorder1 WHERE order_date = '2023-11-11'")
	mcmp.ExecAndNotEmpty("SELECT customer_id and total_amount FROM zcorder1 WHERE order_date = '2023-11-11'")
	mcmp.ExecAndNotEmpty("SELECT SUM(total_amount) FROM zcorder1 WHERE order_date > '2023-10-25'")
	mcmp.ExecAndNotEmpty("SELECT customer_id, COUNT(*) FROM zcorder1 WHERE customer_id = 63 GROUP BY order_date ORDER BY COUNT(*) DESC")
	mcmp.ExecAndNotEmpty("SELECT customer_id, MAX(total_amount) FROM zcorder1 WHERE customer_id = 63 GROUP BY order_date ORDER BY MAX(total_amount) DESC")
	mcmp.ExecAndNotEmpty("SELECT customer_id, MIN(total_amount) FROM zcorder1 WHERE customer_id = 63 GROUP BY order_date ORDER BY MIN(total_amount) ASC")
	mcmp.ExecAndNotEmpty("SELECT customer_id, country FROM zcorder1 WHERE customer_id = 63 GROUP BY order_date ORDER BY product_id DESC")
	mcmp.ExecAndNotEmpty("SELECT customer_id, SUM(total_amount) FROM zcorder1 WHERE customer_id = 63 GROUP BY order_date ORDER BY SUM(total_amount) DESC")
	mcmp.ExecAndNotEmpty("SELECT * FROM zcorder1 WHERE customer_id = 5 AND order_date = '2023-11-11' ORDER BY total_amount DESC LIMIT 10")
	mcmp.ExecAndNotEmpty("SELECT * FROM zcorder1 WHERE customer_id = 20 AND order_date = '2023-11-11' ORDER BY order_id ASC LIMIT 10")
	mcmp.ExecAndNotEmpty("SELECT * FROM zcorder1 WHERE order_date > '2023-10-25' ORDER BY total_amount DESC, order_id ASC LIMIT 10")
	//mcmp.ExecAndNotEmpty("SELECT order_id, total_amount FROM zcorder1 WHERE customer_id = 63 AND order_date = '2023-11-11' GROUP BY order_date HAVING COUNT(*) > 1")
	//mcmp.ExecAndNotEmpty("SELECT order_id, total_amount FROM zcorder1 WHERE customer_id = 63 AND order_date = '2023-11-11' GROUP BY order_date HAVING SUM(total_amount) > 1000")
	mcmp.ExecAndNotEmpty("SELECT COUNT(*) FROM zcorder1 WHERE customer_id = 63 AND order_date > '2023-01-01' AND order_date < '2023-12-31'")
	mcmp.ExecAndNotEmpty("SELECT MAX(total_amount) FROM zcorder1 WHERE customer_id = 63 AND order_date > '2023-01-01' AND order_date < '2023-12-31'")
	mcmp.ExecAndNotEmpty("SELECT MIN(total_amount) FROM zcorder1 WHERE customer_id = 63 AND order_date > '2023-01-01' AND order_date < '2023-12-31'")
	mcmp.ExecAndNotEmpty("SELECT string FROM zcorder1 WHERE customer_id = 63 AND order_date > '2023-01-01' AND order_date < '2023-12-31'")
	mcmp.ExecAndNotEmpty("SELECT SUM(total_amount) FROM zcorder1 WHERE customer_id = 63 AND order_date > '2023-01-01' AND order_date < '2023-12-31'")
	mcmp.ExecAndNotEmpty("SELECT customer_id, COUNT(*) FROM zcorder1 WHERE order_date > '2023-01-01' AND order_date < '2023-12-31' GROUP BY customer_id ORDER BY COUNT(*) DESC")
	mcmp.ExecAndNotEmpty("SELECT customer_id, string FROM zcorder1 WHERE order_date > '2023-01-01' AND order_date < '2023-12-31' GROUP BY customer_id ORDER BY customer_id DESC")
	mcmp.ExecAndNotEmpty("SELECT customer_id, SUM(total_amount) FROM zcorder1 WHERE order_date > '2023-01-01' AND order_date < '2023-12-31' GROUP BY customer_id ORDER BY SUM(total_amount) DESC")
	mcmp.ExecAndNotEmpty("SELECT * FROM zcorder1 WHERE customer_id = 63 AND order_date > '2023-01-01' AND order_date < '2023-12-31' ORDER BY order_date ASC LIMIT 10")
	mcmp.ExecAndNotEmpty("SELECT * FROM zcorder1 WHERE order_date > '2023-01-01' AND order_date < '2023-12-31' ORDER BY product_id DESC, customer_id DESC LIMIT 10")
	mcmp.ExecAndNotEmpty("SELECT COUNT(*) FROM zcorder1 WHERE customer_id = 63 AND order_date > '2023-01-01' AND order_date < '2023-12-31'")
	mcmp.ExecAndNotEmpty("SELECT MAX(total_amount) FROM zcorder1 WHERE customer_id = 63 AND order_date > '2023-01-01' AND order_date < '2023-12-31'")
	mcmp.ExecAndNotEmpty("SELECT MIN(total_amount) FROM zcorder1 WHERE customer_id = 63 AND order_date > '2023-01-01' AND order_date < '2023-12-31'")
	mcmp.ExecAndNotEmpty("SELECT quantity FROM zcorder1 WHERE customer_id = 63 AND order_date > '2023-01-01' AND order_date < '2023-12-31'")
	mcmp.ExecAndNotEmpty("SELECT SUM(total_amount) FROM zcorder1 WHERE customer_id = 63 AND order_date > '2023-01-01' AND order_date < '2023-12-31'")
	mcmp.ExecAndNotEmpty("SELECT customer_id, COUNT(*) FROM zcorder1 WHERE order_date > '2023-01-01' AND order_date < '2023-12-31' GROUP BY customer_id ORDER BY order_id DESC")
	mcmp.ExecAndNotEmpty("SELECT customer_id, SUM(total_amount) FROM zcorder1 WHERE order_date > '2023-01-01' AND order_date < '2023-12-31' GROUP BY customer_id ORDER BY SUM(total_amount) DESC")
	mcmp.ExecAndNotEmpty("SELECT * FROM zcorder1 WHERE customer_id = 63 AND order_date > '2023-01-01' AND order_date < '2023-12-31' ORDER BY order_date ASC LIMIT 10")
	mcmp.ExecAndNotEmpty("SELECT * FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31' ORDER BY customer_id ASC, sequence_id DESC LIMIT 10")
	//mcmp.ExecAndNotEmpty("SELECT * FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31' AND total_amount > 5 ORDER BY total_amount DESC")
	mcmp.ExecAndNotEmpty("SELECT customer_id, count(*) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31' GROUP BY customer_id")
	utils.Exec(t, mcmp.VtConn, "SELECT * FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31' AND product_id IN (SELECT product_id FROM zcorder1 WHERE country = 'China') ORDER BY order_id ASC LIMIT 10")
	mcmp.ExecAndNotEmpty("SELECT order_id, total_amount FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31' AND product_id IN (SELECT product_id FROM zcorder1 WHERE country = 'China') ORDER BY customer_id DESC LIMIT 10")
	mcmp.ExecAndNotEmpty("SELECT order_id, total_amount FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31' AND product_id IN (SELECT product_id FROM zcorder1 WHERE country = 'China') ORDER BY order_id DESC LIMIT 10")
	//mcmp.ExecAndNotEmpty("SELECT order_id FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31' AND customer_id > (SELECT SUM(quantity) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31') ORDER BY total_amount DESC")
	mcmp.ExecAndNotEmpty("SELECT country FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31' AND customer_id > (SELECT MAX(total_amount) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31') ORDER BY total_amount DESC LIMIT 10")
	mcmp.ExecAndNotEmpty("SELECT order_date FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31' AND product_id IN (SELECT product_id FROM zcorder1 WHERE country = 'China') ORDER BY product_id ASC, sequence_id DESC LIMIT 10")
	//mcmp.ExecAndNotEmpty("SELECT COUNT(DISTINCT customer_id), MIN(total_amount), MAX(total_amount) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	mcmp.ExecAndNotEmpty("SELECT  SUM(quantity), MAX(unit_price) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	mcmp.ExecAndNotEmpty("SELECT SUM(total_amount),  COUNT(DISTINCT product_id) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	mcmp.ExecAndNotEmpty("SELECT MIN(unit_price), MAX(unit_price) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	mcmp.ExecAndNotEmpty("SELECT COUNT(DISTINCT order_id),  SUM(quantity), MAX(unit_price) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	mcmp.ExecAndNotEmpty("SELECT SUM(quantity), MAX(unit_price), MIN(total_amount) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	//mcmp.ExecAndNotEmpty("SELECT COUNT(DISTINCT customer_id), MIN(total_amount), MAX(total_amount) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	mcmp.ExecAndNotEmpty("SELECT SUM(total_amount),  COUNT(DISTINCT product_id), MAX(total_amount) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	mcmp.ExecAndNotEmpty("SELECT MIN(unit_price), MAX(unit_price), COUNT(DISTINCT order_id) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	mcmp.ExecAndNotEmpty("SELECT SUM(quantity), MAX(unit_price), MIN(total_amount) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	//mcmp.ExecAndNotEmpty("SELECT SUM(quantity), MAX(unit_price), MIN(total_amount), COUNT(DISTINCT customer_id) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	mcmp.ExecAndNotEmpty("SELECT MIN(total_amount), MAX(total_amount), SUM(total_amount) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	mcmp.ExecAndNotEmpty("SELECT SUM(total_amount), COUNT(DISTINCT product_id), MAX(total_amount), MIN(unit_price) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	mcmp.ExecAndNotEmpty("SELECT MIN(unit_price), MAX(unit_price), COUNT(DISTINCT order_id), SUM(quantity) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	mcmp.ExecAndNotEmpty("SELECT SUM(quantity), MAX(unit_price), MIN(total_amount) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	//mcmp.ExecAndNotEmpty("SELECT SUM(quantity), MAX(unit_price), MIN(total_amount), COUNT(DISTINCT customer_id), MIN(unit_price) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	mcmp.ExecAndNotEmpty("SELECT MIN(total_amount), MAX(total_amount), SUM(total_amount) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	mcmp.ExecAndNotEmpty("SELECT MIN(unit_price), MAX(unit_price), SUM(quantity) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	mcmp.ExecAndNotEmpty("SELECT SUM(quantity), MAX(unit_price), MIN(total_amount) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31'")
	mcmp.ExecAndNotEmpty("SELECT MAX(total_amount), MIN(quantity) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31' GROUP BY product_id ORDER BY product_id ASC LIMIT 10")
	mcmp.ExecAndNotEmpty("SELECT MAX(total_amount), MIN(quantity) FROM zcorder1 WHERE product_id = 50 GROUP BY customer_id, order_date ORDER BY order_date DESC LIMIT 10")
	mcmp.ExecAndNotEmpty("SELECT customer_id, count(*) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31' GROUP BY customer_id")
	mcmp.ExecAndNotEmpty("SELECT MAX(total_amount), MIN(quantity) FROM zcorder1 WHERE order_date BETWEEN '2023-01-01' AND '2023-12-31' GROUP BY customer_id, product_id ORDER BY product_id DESC")
	mcmp.ExecAndNotEmpty("SELECT customer_id, string FROM zcorder1 WHERE order_date > '2023-01-01' AND order_date < '2023-12-31' GROUP BY customer_id ORDER BY sum(total_amount) DESC")
	mcmp.ExecAndNotEmpty("SELECT * FROM zcorder1 ORDER BY order_id DESC")
	mcmp.ExecAndNotEmpty("SELECT * FROM zcorder1 ORDER BY order_id ASC")
	mcmp.ExecAndNotEmpty("SELECT * FROM zcorder1 ORDER BY order_date DESC")
	mcmp.ExecAndNotEmpty("SELECT * FROM zcorder1 ORDER BY order_date ASC")
	mcmp.ExecAndNotEmpty("SELECT * FROM zcorder1 ORDER BY customer_id DESC")
	mcmp.ExecAndNotEmpty("SELECT * FROM zcorder1 ORDER BY customer_id ASC")
	mcmp.ExecAndNotEmpty("SELECT * FROM zcorder1 ORDER BY product_id DESC")
	mcmp.ExecAndNotEmpty("SELECT * FROM zcorder1 ORDER BY product_id ASC")
	mcmp.ExecAndNotEmpty("SELECT * FROM zcorder1 ORDER BY sequence_id DESC")
	mcmp.ExecAndNotEmpty("SELECT * FROM zcorder1 ORDER BY sequence_id ASC")
	utils.Exec(t, mcmp.VtConn, "SELECT * FROM zcorder1")
	utils.Exec(t, mcmp.VtConn, "SELECT * FROM zcorder1 limit 10")
	mcmp.ExecAndNotEmpty("SELECT * FROM zcorder1 WHERE customer_id = 63")
	mcmp.ExecAndNotEmpty("SELECT * FROM zcorder1 WHERE product_id = 63 LIMIT 10")

}
